/**
 * 베트남 내 주요 은행 목록 (배당금 수령 계좌 선택용).
 * 은행명은 고유명사이므로 언어별 번역을 적용하지 않는다.
 */
export const VIETNAM_BANKS: string[] = [
  "Vietcombank",
  "VietinBank",
  "BIDV",
  "Agribank",
  "Techcombank",
  "MB Bank",
  "ACB",
  "VPBank",
  "Sacombank",
  "HDBank",
  "SHB",
  "TPBank",
  "VIB",
  "Eximbank",
  "MSB",
  "SeABank",
  "OCB",
  "LPBank",
  "Nam A Bank",
  "ABBank",
  "Bac A Bank",
  "VietBank",
  "Viet A Bank",
  "PVcomBank",
  "Kienlongbank",
  "NCB",
  "BaoViet Bank",
  "SaigonBank",
  "PGBank",
  "VRB",
  "GPBank",
  "MBV (OceanBank)",
  "CBBank",
  "Public Bank Vietnam",
  "Woori Bank Vietnam",
  "Shinhan Bank Vietnam",
  "HSBC Vietnam",
  "Standard Chartered Vietnam",
  "UOB Vietnam",
  "CIMB Vietnam",
];
